4 1 amd cleanup
anthology-ally/moodle-filter_ally pull request #33
Opened 2023-05-29 09:48 UTC by gthomas2

2023-06-06 08:18 UTC, mmihalek-bb requested changes

2023-06-06 08:18 UTC, mmihalek-bb commented on .github/workflows/moodle-ci.yml
> +  # debug:
cleanup the comments?

2023-06-06 08:18 UTC, mmihalek-bb commented on README.md
> +![example workflow](https://github.com/gthomas2/moodle-filter_ally/actions/workflows/moodle-ci.yml/badge.svg)
update the link reference?

2023-06-08 17:04 UTC, tomas-ruzicka commented
@gthomas2 - during the testing we discovered that the plugins show '4.0.7' release version.

2023-06-09 20:08 UTC, tomas-ruzicka approved these changes

2023-06-09 20:09 UTC, merged